### ISSUE TITLE
CSV-Download von Trefferlisten

### ISSUE THREAD

**Issue by rsteph-de** [MyCoRe-Org/professorenkatalog#5]
Als erste "schnelle" Lösung soll ein Link für die Search-API generiert werden

**Comment by golsch** [comment]
Es wäre sinnvoll, die Felder: `profkat.birthdate`, `profkat.birthplace`, `profkat.deathdath`, `profkat.deathplace` standardmäßig in der CSV miteinzubeziehen.

**Comment by rsteph-de** [comment]
wurden bereits in den mycore.properties ergänzt -> Download funktioniert
